installer:
  build: docker-images/magento_installer
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
    MAGE_IS_DEVELOPER_MODE: 1
  volumes_from:
    - nginx
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  extra_hosts:
    - "dockerhost:$DOCKERHOST"

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./data/logs:/var/log/nginx
    - ./data/config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./data/config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./data/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./data/config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./data/config/nginx/includes:/etc/nginx/includes
    - ./data/config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
  environment:
    MAGE_IS_DEVELOPER_MODE: 1

php:
  build: docker-images/magento_php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  volumes:
    - ./data/root:/var/www/html
  extra_hosts:
    - "dockerhost:$DOCKERHOST"
  environment:
    MAGE_IS_DEVELOPER_MODE: 1

mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mysql:/var/lib/mysql

solr:
  build: docker-images/magento_solr

cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest
