#!/usr/bin/env bash

export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
echo "Using DOCKERHOST: $DOCKERHOST"

case "$1" in
  "start")
    docker-compose up -d
  ;;

  "follow")
    docker-compose logs -f
  ;;

  "stop")
    docker-compose stop
  ;;

  "destroy")
    echo "This action will destroy all related containers as well as associated data."
    read -p "Are you sure? [y|N] " -n 1 -r; echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
      echo "Aborting mission... Close call!"
      exit 0
    fi
    docker-compose stop
    docker-compose rm -fv
    sudo rm -rf data/mysql \
                data/logs/* \
                data/root/web data/root/vendor data/root/composer.lock
esac
